<?php

namespace Jp\YahooApis\SS\V201909\FeedItem;

class FeedItemPlaceholderField
{
    const __default = 'LINK_TEXT';
    const LINK_TEXT = 'LINK_TEXT';
    const LINK_URL = 'LINK_URL';
    const LINK_DESCRIPTION_1 = 'LINK_DESCRIPTION_1';
    const LINK_DESCRIPTION_2 = 'LINK_DESCRIPTION_2';
    const ADVANCED_URL = 'ADVANCED_URL';
    const ADVANCED_MOBILE_URL = 'ADVANCED_MOBILE_URL';
    const TRACKING_URL = 'TRACKING_URL';
    const CALL_PHONE_NUMBER = 'CALL_PHONE_NUMBER';
    const AD_CUSTOMIZER_INTEGER = 'AD_CUSTOMIZER_INTEGER';
    const AD_CUSTOMIZER_PRICE = 'AD_CUSTOMIZER_PRICE';
    const AD_CUSTOMIZER_DATE = 'AD_CUSTOMIZER_DATE';
    const AD_CUSTOMIZER_STRING = 'AD_CUSTOMIZER_STRING';
    const CALLOUT_TEXT = 'CALLOUT_TEXT';
    const ADDITIONAL_ADVANCED_URLS = 'ADDITIONAL_ADVANCED_URLS';
    const ADDITIONAL_ADVANCED_MOBILE_URLS = 'ADDITIONAL_ADVANCED_MOBILE_URLS';
    const STRUCTURED_SNIPPET_HEADER = 'STRUCTURED_SNIPPET_HEADER';
    const STRUCTURED_SNIPPET_VALUES = 'STRUCTURED_SNIPPET_VALUES';


}
