<?php

namespace Jp\YahooApis\SS\V201901\FeedFolder;

class FeedFolderPlaceholderField
{
    const __default = 'AD_CUSTOMIZER_INTEGER';
    const AD_CUSTOMIZER_INTEGER = 'AD_CUSTOMIZER_INTEGER';
    const AD_CUSTOMIZER_PRICE = 'AD_CUSTOMIZER_PRICE';
    const AD_CUSTOMIZER_DATE = 'AD_CUSTOMIZER_DATE';
    const AD_CUSTOMIZER_STRING = 'AD_CUSTOMIZER_STRING';
    const DYNAMIC_AD_FOR_SEARCH_PAGE_FEEDS_PAGE_URL = 'DYNAMIC_AD_FOR_SEARCH_PAGE_FEEDS_PAGE_URL';
    const DYNAMIC_AD_FOR_SEARCH_PAGE_FEEDS_LABEL = 'DYNAMIC_AD_FOR_SEARCH_PAGE_FEEDS_LABEL';


}
