<?php

namespace Jp\YahooApis\SS\V201901\Campaign;

class BiddingStrategyFailedReason
{
    const __default = 'FAILURE';
    const FAILURE = 'FAILURE';
    const CONVERSION_TRACKING_NOT_ENABLED = 'CONVERSION_TRACKING_NOT_ENABLED';
    const NOT_ENOUGH_CONVERSIONS = 'NOT_ENOUGH_CONVERSIONS';
    const CANNOT_CREATE_CAMPAIGN_WITH_CONVERSION_OPTIMIZER = 'CANNOT_CREATE_CAMPAIGN_WITH_CONVERSION_OPTIMIZER';
    const BIDDING_STRATEGY_CANNOT_BE_OVERRIDDEN = 'BIDDING_STRATEGY_CANNOT_BE_OVERRIDDEN';
    const NOT_CPC_CAMPAIGN = 'NOT_CPC_CAMPAIGN';


}
