<?php

namespace Jp\YahooApis\SS\V201909\Campaign;

class SettingType
{
    const __default = 'GEO_TARGET_TYPE_SETTING';
    const GEO_TARGET_TYPE_SETTING = 'GEO_TARGET_TYPE_SETTING';
    const TARGET_LIST_SETTING = 'TARGET_LIST_SETTING';
    const DYNAMIC_ADS_FOR_SEARCH_SETTING = 'DYNAMIC_ADS_FOR_SEARCH_SETTING';


}
