<?php

namespace Jp\YahooApis\SS\V201901\AdGroupAd;

class TrademarkStatus
{
    const __default = 'NO_RESTRICTION';
    const NO_RESTRICTION = 'NO_RESTRICTION';
    const CONFLICT_WITH_TRADEMARK = 'CONFLICT_WITH_TRADEMARK';
    const CLAIM_IN_PROGRESS = 'CLAIM_IN_PROGRESS';
    const DISAPPROVED_CLAIM = 'DISAPPROVED_CLAIM';
    const DISAPPROVED_REVIEWER = 'DISAPPROVED_REVIEWER';


}
