<?php

namespace Jp\YahooApis\SS\V201901\PageFeedItem;

class PageFeedItemUploadJobStatus
{
    const __default = 'IN_PROGRESS';
    const IN_PROGRESS = 'IN_PROGRESS';
    const COMPLETED = 'COMPLETED';
    const COMPLETED_WITH_VALIDATION_ERROR = 'COMPLETED_WITH_VALIDATION_ERROR';
    const FILE_FORMAT_ERROR = 'FILE_FORMAT_ERROR';
    const FILE_ENCODING_ERROR = 'FILE_ENCODING_ERROR';
    const COLUMN_HEADER_ERROR = 'COLUMN_HEADER_ERROR';
    const EXCEED_ROW_LINES = 'EXCEED_ROW_LINES';
    const EXCEED_FILE_COUNTS = 'EXCEED_FILE_COUNTS';
    const INVALID_FEED_FOLDER_ID = 'INVALID_FEED_FOLDER_ID';
    const TIMEOUT = 'TIMEOUT';
    const SYSTEM_ERROR = 'SYSTEM_ERROR';


}
